name: Deploy to pages

on:
  workflow_dispatch: {}
  push:
    branches: [master]
  schedule:
    - cron: '2 * * * *' # every hour

jobs:
  check-updates:
    runs-on: ubuntu-latest
    outputs:
      has-update: ${{ steps.check.outputs.has-update }}
    steps:
      - name: Configure Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Check for updates
        id: check
        shell: bash
        run: |
          set -e
          deployed="$(curl -fsS ${{ steps.pages.outputs.base_url }}/master.zip.sig || true)"
          upstream=$(curl -fsS ${{ secrets.CHARWASP_MANIFEST_URL }} | jq -r '.assets["master.zip"].md5')
          if [[ -z "$deployed" || "$upstream" != "$deployed" ]]; then
            echo 'has-update=true' >> $GITHUB_OUTPUT
          else
            echo 'has-update=false' >> $GITHUB_OUTPUT
          fi

  build:
    needs: check-updates
    if: needs.check-updates.outputs.has-update == 'true' || github.event_name != 'schedule'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        id: setup-ruby
        with:
          ruby-version: '3.2' # minify_html=0.15.0 requires < 3.3; see Gemfile
          bundler-cache: true
        env:
          BUNDLE_WITHOUT: development:optional

      - name: Configure Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Restore additional music data
        run: |
          set -e
          curl -fsSL $(curl -fsS -w '%{redirect_url}\n' https://gist.github.com/${{ secrets.GIST_ID }})/raw > data/music.json

      - name: Build
        run: bundle exec rake
        env:
          BUNDLE_WITHOUT: development:optional
          CHARWASP_SITE_URL: ${{ steps.pages.outputs.base_url }}
          CHARWASP_MANIFEST_URL: ${{ secrets.CHARWASP_MANIFEST_URL }}
          SOUNDCLOUD_OAUTH_TOKEN: ${{ secrets.SOUNDCLOUD_OAUTH_TOKEN }}
          INVIDIOUS_HOST: ${{ secrets.INVIDIOUS_HOST }}
          CHARWASP_GITHUB_REPO_URL: https://github.com/${{ github.repository }}

      - name: Update additional music data
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: ${{ secrets.GIST_ID }}
          file_path: data/music.json

      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/

  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
